#!/bin/sh

mkdir -p ~/.TeXmacs

if [ "$(ls -A /app/texlive)" ]; then
  architecture_type=$(uname -m)
  perl_version=$(ls /app/texlive/lib/perl5/site_perl/)

  if ! [[ $perl_version =~ ^[0-9.]+$ ]]; then
    echo " startTeXmacs.sh: Possible error in environment variables."
    echo " "
  fi

  PATH=/app/texlive/bin/${architecture_type}-linux:${PATH}
  export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/app/texlive/lib/perl5/${perl_version}/${architecture_type}-linux/CORE
  export PERL5LIB=/app/texlive/lib/perl5/${perl_version}:/app/texlive/lib/perl5/site_perl/${perl_version}
fi

for DIR in /app/plugins/*; do
  if [ -d "$DIR/bin" ]; then
    PATH="$DIR/bin:$PATH"
  fi
done

export PATH
export PYTHONPATH=/app/plugins/cadabra/lib/python3.12/site-packages

# Archivo de configuracion
config_file="flat-config.conf"
path_config_file=~/.TeXmacs
IDN="1"
if [[ -f "${path_config_file}/${config_file}" ]]; then

    source "${path_config_file}/${config_file}"

    if [[ "$ID" == "$IDN" ]]; then
      exec texmacs-bin "$@"
    else
      echo "ID=$IDN" > "${path_config_file}/${config_file}"
      exec texmacs-bin /app/share/texmacs-flatpak/firts_run.tm
    fi
else
    touch "${path_config_file}/${config_file}"
    echo "ID=$IDN" > "${path_config_file}/${config_file}"
    exec texmacs-bin /app/share/texmacs-flatpak/firts_run.tm
fi

